#!/bin/sh

mkdir downloaded_fonts && cd downloaded_fonts
wget http://www.figlet.org/fonts/3-d.flf &&
wget http://www.figlet.org/fonts/3x5.flf &&
wget http://www.figlet.org/fonts/5lineoblique.flf &&
wget http://www.figlet.org/fonts/acrobatic.flf &&
wget http://www.figlet.org/fonts/alligator.flf &&
wget http://www.figlet.org/fonts/alligator2.flf &&
wget http://www.figlet.org/fonts/alphabet.flf &&
wget http://www.figlet.org/fonts/avatar.flf &&
wget http://www.figlet.org/fonts/banner.flf &&
wget http://www.figlet.org/fonts/banner3-D.flf &&
wget http://www.figlet.org/fonts/banner3.flf &&
wget http://www.figlet.org/fonts/banner4.flf &&
wget http://www.figlet.org/fonts/barbwire.flf &&
wget http://www.figlet.org/fonts/basic.flf &&
wget http://www.figlet.org/fonts/bell.flf &&
wget http://www.figlet.org/fonts/big.flf &&
wget http://www.figlet.org/fonts/bigchief.flf &&
wget http://www.figlet.org/fonts/binary.flf &&
wget http://www.figlet.org/fonts/block.flf &&
wget http://www.figlet.org/fonts/bubble.flf &&
wget http://www.figlet.org/fonts/bulbhead.flf &&
wget http://www.figlet.org/fonts/calgphy2.flf &&
wget http://www.figlet.org/fonts/caligraphy.flf &&
wget http://www.figlet.org/fonts/catwalk.flf &&
wget http://www.figlet.org/fonts/chunky.flf &&
wget http://www.figlet.org/fonts/coinstak.flf &&
wget http://www.figlet.org/fonts/colossal.flf &&
wget http://www.figlet.org/fonts/computer.flf &&
wget http://www.figlet.org/fonts/contessa.flf &&
wget http://www.figlet.org/fonts/contrast.flf &&
wget http://www.figlet.org/fonts/cosmic.flf &&
wget http://www.figlet.org/fonts/cosmike.flf &&
wget http://www.figlet.org/fonts/cricket.flf &&
wget http://www.figlet.org/fonts/cursive.flf &&
wget http://www.figlet.org/fonts/cyberlarge.flf &&
wget http://www.figlet.org/fonts/cybermedium.flf &&
wget http://www.figlet.org/fonts/cybersmall.flf &&
wget http://www.figlet.org/fonts/diamond.flf &&
wget http://www.figlet.org/fonts/digital.flf &&
wget http://www.figlet.org/fonts/doh.flf &&
wget http://www.figlet.org/fonts/doom.flf &&
wget http://www.figlet.org/fonts/dotmatrix.flf &&
wget http://www.figlet.org/fonts/drpepper.flf &&
wget http://www.figlet.org/fonts/eftichess.flf &&
wget http://www.figlet.org/fonts/eftifont.flf &&
wget http://www.figlet.org/fonts/eftipiti.flf &&
wget http://www.figlet.org/fonts/eftirobot.flf &&
wget http://www.figlet.org/fonts/eftitalic.flf &&
wget http://www.figlet.org/fonts/eftiwall.flf &&
wget http://www.figlet.org/fonts/eftiwater.flf &&
wget http://www.figlet.org/fonts/epic.flf &&
wget http://www.figlet.org/fonts/fender.flf &&
wget http://www.figlet.org/fonts/fourtops.flf &&
wget http://www.figlet.org/fonts/fuzzy.flf &&
wget http://www.figlet.org/fonts/goofy.flf &&
wget http://www.figlet.org/fonts/gothic.flf &&
wget http://www.figlet.org/fonts/graffiti.flf &&
wget http://www.figlet.org/fonts/hollywood.flf &&
wget http://www.figlet.org/fonts/invita.flf &&
wget http://www.figlet.org/fonts/isometric1.flf &&
wget http://www.figlet.org/fonts/isometric2.flf &&
wget http://www.figlet.org/fonts/isometric3.flf &&
wget http://www.figlet.org/fonts/isometric4.flf &&
wget http://www.figlet.org/fonts/italic.flf &&
wget http://www.figlet.org/fonts/ivrit.flf &&
wget http://www.figlet.org/fonts/jazmine.flf &&
wget http://www.figlet.org/fonts/jerusalem.flf &&
wget http://www.figlet.org/fonts/katakana.flf &&
wget http://www.figlet.org/fonts/kban.flf &&
wget http://www.figlet.org/fonts/larry3d.flf &&
wget http://www.figlet.org/fonts/lcd.flf &&
wget http://www.figlet.org/fonts/lean.flf &&
wget http://www.figlet.org/fonts/letters.flf &&
wget http://www.figlet.org/fonts/linux.flf &&
wget http://www.figlet.org/fonts/lockergnome.flf &&
wget http://www.figlet.org/fonts/madrid.flf &&
wget http://www.figlet.org/fonts/marquee.flf &&
wget http://www.figlet.org/fonts/maxfour.flf &&
wget http://www.figlet.org/fonts/mike.flf &&
wget http://www.figlet.org/fonts/mini.flf &&
wget http://www.figlet.org/fonts/mirror.flf &&
wget http://www.figlet.org/fonts/mnemonic.flf &&
wget http://www.figlet.org/fonts/morse.flf &&
wget http://www.figlet.org/fonts/moscow.flf &&
wget http://www.figlet.org/fonts/nancyj-fancy.flf &&
wget http://www.figlet.org/fonts/nancyj-underlined.flf &&
wget http://www.figlet.org/fonts/nancyj.flf &&
wget http://www.figlet.org/fonts/nipples.flf &&
wget http://www.figlet.org/fonts/ntgreek.flf &&
wget http://www.figlet.org/fonts/o8.flf &&
wget http://www.figlet.org/fonts/ogre.flf &&
wget http://www.figlet.org/fonts/pawp.flf &&
wget http://www.figlet.org/fonts/peaks.flf &&
wget http://www.figlet.org/fonts/pebbles.flf &&
wget http://www.figlet.org/fonts/pepper.flf &&
wget http://www.figlet.org/fonts/poison.flf &&
wget http://www.figlet.org/fonts/puffy.flf &&
wget http://www.figlet.org/fonts/pyramid.flf &&
wget http://www.figlet.org/fonts/rectangles.flf &&
wget http://www.figlet.org/fonts/relief.flf &&
wget http://www.figlet.org/fonts/relief2.flf &&
wget http://www.figlet.org/fonts/rev.flf &&
wget http://www.figlet.org/fonts/roman.flf &&
wget http://www.figlet.org/fonts/rot13.flf &&
wget http://www.figlet.org/fonts/rounded.flf &&
wget http://www.figlet.org/fonts/rowancap.flf &&
wget http://www.figlet.org/fonts/rozzo.flf &&
wget http://www.figlet.org/fonts/runic.flf &&
wget http://www.figlet.org/fonts/runyc.flf &&
wget http://www.figlet.org/fonts/sblood.flf &&
wget http://www.figlet.org/fonts/script.flf &&
wget http://www.figlet.org/fonts/serifcap.flf &&
wget http://www.figlet.org/fonts/shadow.flf &&
wget http://www.figlet.org/fonts/short.flf &&
wget http://www.figlet.org/fonts/slant.flf &&
wget http://www.figlet.org/fonts/slide.flf &&
wget http://www.figlet.org/fonts/slscript.flf &&
wget http://www.figlet.org/fonts/small.flf &&
wget http://www.figlet.org/fonts/smisome1.flf &&
wget http://www.figlet.org/fonts/smkeyboard.flf &&
wget http://www.figlet.org/fonts/smscript.flf &&
wget http://www.figlet.org/fonts/smshadow.flf &&
wget http://www.figlet.org/fonts/smslant.flf &&
wget http://www.figlet.org/fonts/smtengwar.flf &&
wget http://www.figlet.org/fonts/speed.flf &&
wget http://www.figlet.org/fonts/stampatello.flf &&
wget http://www.figlet.org/fonts/standard.flf &&
wget http://www.figlet.org/fonts/starwars.flf &&
wget http://www.figlet.org/fonts/stellar.flf &&
wget http://www.figlet.org/fonts/stop.flf &&
wget http://www.figlet.org/fonts/straight.flf &&
wget http://www.figlet.org/fonts/tanja.flf &&
wget http://www.figlet.org/fonts/tengwar.flf &&
wget http://www.figlet.org/fonts/term.flf &&
wget http://www.figlet.org/fonts/thick.flf &&
wget http://www.figlet.org/fonts/thin.flf &&
wget http://www.figlet.org/fonts/threepoint.flf &&
wget http://www.figlet.org/fonts/ticks.flf &&
wget http://www.figlet.org/fonts/ticksslant.flf &&
wget http://www.figlet.org/fonts/tinker-toy.flf &&
wget http://www.figlet.org/fonts/tombstone.flf &&
wget http://www.figlet.org/fonts/trek.flf &&
wget http://www.figlet.org/fonts/tsalagi.flf &&
wget http://www.figlet.org/fonts/twopoint.flf &&
wget http://www.figlet.org/fonts/univers.flf &&
wget http://www.figlet.org/fonts/usaflag.flf &&
wget http://www.figlet.org/fonts/wavy.flf &&
wget http://www.figlet.org/fonts/weird.flf
